moved iOS + Android build code to cmakemake script

diff --git a/utils/cmakemake b/utils/cmakemake
--- a/utils/cmakemake
+++ b/utils/cmakemake
@@ -1,11 +1,7 @@
 #!/bin/sh
 set -e
 
-case $1 in 
-clean)
-    DO_CLEAN=1
-    shift
-    ;;
+case $1 in
 install)
     DO_INSTALL=1
     shift
@@ -16,11 +12,9 @@ while [ $# -gt 0 ]; do
     OPT=$1
 
     case $OPT in
-    -j*|-D*|-U*)
-        if [ -z ${OPT:2} ]; then
-            shift
-            OPT="$OPT$1"
-        fi
+    -j|-D|-U|-G)
+        shift
+        OPT="$OPT$1"
         ;;
     esac
 
@@ -29,18 +23,25 @@ while [ $# -gt 0 ]; do
         cat <<E0
 Usage: cmakemake [<build-options>] <project-dir>
   or   cmakemake install [--debug] <project-dir>
-  or   cmakemake clean <project-dir>
 
 Build options:
 
   --debug               Debug build
   --release             Release build (default)
-  --target="xcode"      Generate and build Xcode project
   --no-build            Generate project, but don't build
+  --platform=<name>     Build for another platform (see below)
   --prefix=<path>       Set install prefix
   -j<cpu-count>         Set compiler job count
   -D<variable>=<value>  Define a cmake variable
   -U<variable>          Undefine a cmake variable
+  -G<generator>         Use a cmake generator
+
+Supported platforms:
+
+  * Android             Build Android binaries (armeabi-v7a) (MSYS, Linux, OS X)
+  * iOS                 Build iOS binaries (iphoneos+simulator) (OS X only)
+  * Xcode               Build using Xcode (debug+release) (OS X only)
+
 
 Build script for CMake projects.
 
@@ -49,7 +50,8 @@ This command wraps 'cmake && make' with some additional features:
   - Out of source builds with debug and release built to separate folders
   - Paralell builds out of the box
   - Xcode batch builds (OS X only)
-  - MSYS builds (Windows only)
+  - MSYS support (Windows only)
+  - iOS + Android cross builds
 
 Additional arguments to cmake can be passed using environment variable CMAKE_ARGS.
 E0
@@ -64,20 +66,17 @@ E0
     --no-build)
         DO_BUILD=0
         ;;
-    --target=*)
-        TARGET="${OPT:9}"
+    --platform=*)
+        PLATFORM=`echo ${OPT:11} | tr '[:upper:]' '[:lower:]'`
         ;;
     --prefix=*)
         CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${OPT:9}"
         ;;
+    -D*|-U*|-G*)
+        CMAKE_ARGS="$CMAKE_ARGS -${OPT:1}"
+        ;;
     -j*)
         JOB_COUNT="${OPT:2}"
-        ;;
-    -D*)
-        CMAKE_ARGS="$CMAKE_ARGS -D${OPT:2}"
-        ;;
-    -U*)
-        CMAKE_ARGS="$CMAKE_ARGS -U${OPT:2}"
         ;;
     --)
         shift
@@ -106,34 +105,21 @@ if [ -z "$PROJECT_DIR" ]; then
 fi
 
 cd "$PROJECT_DIR"
+PROJECT_DIR=`pwd -P` # Absolute path
 
-if [ "$DO_CLEAN" = "1" ]; then
-    for dir in "build/release" "build/debug"; do
-        if [ -f "$dir/Makefile" ]; then
-            cd "$dir"
-            make clean || true
-            cd "$OLDPWD"
-        fi
-    done
+cd "`dirname "$0"`/.."
+XLI_DIR=`pwd -P`
 
-    if [ -d "build/xcode" ]; then
-        cd build/xcode
-        xcodebuild -alltargets -configuration Debug clean || true
-        xcodebuild -alltargets -configuration Release clean || true
-        cd "$OLDPWD"
-    fi
-
-    rm -rfv build
-    exit 0
-fi
+cd "$PROJECT_DIR"
 
 if [ "$DEBUG" = "1" ]; then
-    BUILD_DIR="build/debug"
-    CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_BUILD_TYPE:STRING=Debug"
+    BUILD_TYPE="Debug"
 else
-    BUILD_DIR="build/release"
-    CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_BUILD_TYPE:STRING=Release"
+    BUILD_TYPE="Release"
 fi
+
+BUILD_DIR="build/$BUILD_TYPE"
+CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
 
 if [ "$DO_INSTALL" = "1" ]; then
     cd "$BUILD_DIR"
@@ -151,33 +137,6 @@ if ! which cmake > /dev/null 2>&1; then
     fi
 fi
 
-if [ -n "$TARGET" ]; then
-    case $TARGET in
-    xcode)
-        mkdir -p build/xcode
-        cd build/xcode
-
-        cmake ../.. -GXcode $CMAKE_ARGS
-
-        if [ "$DO_BUILD" != "0" ]; then
-            if [ -z "$DEBUG" ] || [ "$DEBUG" == "1" ]; then
-                xcodebuild -alltargets -configuration Debug
-            fi
-
-            if [ -z "$DEBUG" ] || [ "$DEBUG" == "0" ]; then
-                xcodebuild -alltargets -configuration Release
-            fi
-        fi
-
-        exit 0
-        ;;
-    *)
-        echo "ERROR: Invalid target '$TARGET'.\n\nType \`cmakemake --help\` for usage." >&2
-        exit 1
-        ;;
-    esac
-fi
-
 if [ -z "$JOB_COUNT" ]; then
     if [ -f /proc/cpuinfo ]; then
         JOB_COUNT=`grep processor /proc/cpuinfo | wc -l`
@@ -190,18 +149,101 @@ if [ -z "$JOB_COUNT" ]; then
     fi
 fi
 
-mkdir -p "$BUILD_DIR"
-cd "$BUILD_DIR"
-
-#rm -f CMakeCache.txt
-
-if [ "$OSTYPE" = "msys" ]; then
-    export CMAKE_ARGS="$CMAKE_ARGS -G\"MSYS Makefiles"
-    cmd "/C cmake ../.. %CMAKE_ARGS%"
+if [ "$DO_BUILD" != "0" ]; then
+    case $DEBUG in
+    0)
+        CONFIGS="Release"
+        ;;
+    1)
+        CONFIGS="Debug"
+        ;;
+    *)
+        CONFIGS="Release Debug"
+        ;;
+    esac
 else
-    cmake ../.. $CMAKE_ARGS
+    CONFIGS=""
 fi
 
-if [ "$DO_BUILD" != "0" ]; then
-    make -j "$JOB_COUNT"
+if [ -n "$PLATFORM" ]; then
+    case $PLATFORM in
+    xcode)
+        mkdir -p build/Xcode
+        cd build/Xcode
+
+        cmake ../.. -GXcode $CMAKE_ARGS
+
+        for cfg in $CONFIGS; do
+            xcodebuild -alltargets -configuration "$cfg"
+        done
+        ;;
+    ios)
+        set -- ../../.. $CMAKE_ARGS -GXcode -DCMAKE_TOOLCHAIN_FILE="$XLI_DIR/cmake/toolchain/iOS.cmake"
+
+        for arch in OS SIMULATOR; do
+            mkdir -p "build/iOS/$arch"
+            cd "build/iOS/$arch"
+
+            cmake "$@" -DIOS_PLATFORM="$arch"
+
+            for cfg in $CONFIGS; do
+                xcodebuild -alltargets -configuration "$cfg"
+            done
+
+            cd "$PROJECT_DIR"
+        done
+        ;;
+    android)
+        NDK_FILENAME=`which ndk-build`
+        NDK_DIR=`dirname "$NDK_FILENAME"`
+        NDK_ABI="armeabi-v7a"
+        TOOLCHAIN_FILE="$XLI_DIR/cmake/toolchain/android.toolchain.cmake"
+        BUILD_DIR="build/android/$BUILD_TYPE-$NDK_ABI"
+
+        mkdir -p "$BUILD_DIR"
+        cd "$BUILD_DIR"
+
+        if [ "$OSTYPE" = "msys" ]; then
+            # TODO: Try to replace this stuff with `cmake --build .`
+            if [ -d "$NDK_DIR/prebuilt/windows-x86_64/bin" ]; then
+                MAKE_DIR="$NDK_DIR/prebuilt/windows-x86_64/bin"
+            else
+                MAKE_DIR="$NDK_DIR/prebuilt/windows-x86_32/bin"
+            fi
+
+            CMAKE_FILENAME=`which cmake`
+            CMAKE_DIR=`dirname "$CMAKE_FILENAME"`
+            PATH="$CMAKE_DIR:$MAKE_DIR"
+            set -- -G"MinGW Makefiles"
+        fi
+
+        set -- -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE" "$@"
+        set -- -DANDROID_NDK="$NDK_DIR" -DANDROID_ABI="$NDK_ABI" "$@"
+        set -- -DANDROID_NATIVE_API_LEVEL="android-9" -DANDROID_STL="stlport_static" "$@"
+
+        cmake "$@" $CMAKE_ARGS ../../..
+
+        if [ "$DO_BUILD" != "0" ]; then
+            cmake --build . --use-stderr -- -j "$JOB_COUNT"
+        fi
+        ;;
+    *)
+        echo "ERROR: Invalid platform '$PLATFORM'.\n\nType \`cmakemake --help\` for usage." >&2
+        exit 1
+        ;;
+    esac
+else
+    mkdir -p "$BUILD_DIR"
+    cd "$BUILD_DIR"
+
+    if [ "$OSTYPE" = "msys" ]; then
+        export CMAKE_ARGS="$CMAKE_ARGS -G\"MSYS Makefiles"
+        cmd "/C cmake ../.. %CMAKE_ARGS%"
+    else
+        cmake ../.. $CMAKE_ARGS
+    fi
+
+    if [ "$DO_BUILD" != "0" ]; then
+        cmake --build . --use-stderr -- -j "$JOB_COUNT"
+    fi
 fi
